build:
	go build -ldflags="-X 'main.buildVersion=v1.0.0' -X 'main.buildDate=$(date)'" client-password
run:
	go run client-password -ldflags="-X 'main.buildVersion=v1.0.0' -X 'main.buildDate=$(date)'"


// я забыл сделать вторую ветку, поэтому такой не удобный МР))